// <auto-generated />
using System;
using GNBSsys.GerenciaDespesas.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GNBSys.GerenciaDespesas.Infra.Data.Migrations
{
    [DbContext(typeof(GerenciaDespesaContext))]
    [Migration("20190708012023_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Despesa", b =>
                {
                    b.Property<Guid>("DespesaId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MesId");

                    b.Property<Guid>("TipoDespesaId");

                    b.Property<double>("Valor");

                    b.HasKey("DespesaId");

                    b.HasIndex("MesId");

                    b.HasIndex("TipoDespesaId");

                    b.ToTable("TDespesa");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Mes", b =>
                {
                    b.Property<int>("MesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MesId");

                    b.ToTable("TMes");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Salario", b =>
                {
                    b.Property<Guid>("SalarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MesId");

                    b.Property<double>("Valor");

                    b.HasKey("SalarioId");

                    b.HasIndex("MesId")
                        .IsUnique();

                    b.ToTable("TSalario");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.TipoDespesa", b =>
                {
                    b.Property<Guid>("TipoDespesaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("TipoDespesaId");

                    b.ToTable("TTipoDespesa");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Despesa", b =>
                {
                    b.HasOne("GNBSys.GerenciaDespesas.Domain.Entities.Mes", "Mes")
                        .WithMany("Despesas")
                        .HasForeignKey("MesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GNBSys.GerenciaDespesas.Domain.Entities.TipoDespesa", "TipoDepesa")
                        .WithMany("Despesas")
                        .HasForeignKey("TipoDespesaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Salario", b =>
                {
                    b.HasOne("GNBSys.GerenciaDespesas.Domain.Entities.Mes", "Mes")
                        .WithOne("Salario")
                        .HasForeignKey("GNBSys.GerenciaDespesas.Domain.Entities.Salario", "MesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
