// <auto-generated />
using System;
using GNBSsys.GerenciaDespesas.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GNBSys.GerenciaDespesas.Infra.Data.Migrations
{
    [DbContext(typeof(GerenciaDespesaContext))]
    partial class GerenciaDespesaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Despesa.Despesa", b =>
                {
                    b.Property<Guid>("DespesaId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MesId");

                    b.Property<Guid>("TipoDespesaId");

                    b.Property<double>("Valor");

                    b.HasKey("DespesaId");

                    b.HasIndex("MesId");

                    b.HasIndex("TipoDespesaId");

                    b.ToTable("TDespesa");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Despesa.TipoDespesa", b =>
                {
                    b.Property<Guid>("TipoDespesaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("TipoDespesaId");

                    b.ToTable("TTipoDespesa");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Mes", b =>
                {
                    b.Property<int>("MesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MesId");

                    b.ToTable("TMes");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Receita.Ativo", b =>
                {
                    b.Property<Guid>("AtivoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid>("TipoAtivoId");

                    b.HasKey("AtivoId");

                    b.HasIndex("TipoAtivoId");

                    b.ToTable("TAtivo");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Receita.AtivoCarteira", b =>
                {
                    b.Property<Guid>("AtivoId");

                    b.Property<Guid>("CarteiraId");

                    b.HasKey("AtivoId", "CarteiraId");

                    b.HasIndex("CarteiraId");

                    b.ToTable("TAtivoCarteira");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Receita.Carteira", b =>
                {
                    b.Property<Guid>("CarteiraId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<double>("Valor");

                    b.HasKey("CarteiraId");

                    b.ToTable("TCarteira");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Receita.MovimentacaoCarteira", b =>
                {
                    b.Property<Guid>("MovimentacaoCarteiraId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AtivoId");

                    b.Property<Guid>("CarteiraId");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<DateTime>("DataMovimentacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("MesId");

                    b.Property<int>("TipoMovimentacaoCarteiraId");

                    b.Property<double>("Valor");

                    b.HasKey("MovimentacaoCarteiraId");

                    b.HasIndex("AtivoId");

                    b.HasIndex("CarteiraId");

                    b.HasIndex("MesId");

                    b.HasIndex("TipoMovimentacaoCarteiraId");

                    b.ToTable("TMovimentacaoCarteira");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Receita.TipoAtivo", b =>
                {
                    b.Property<Guid>("TipoAtivoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("TipoAtivoId");

                    b.ToTable("TTipoAtivo");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Receita.TipoMovimentacaoCarteira", b =>
                {
                    b.Property<int>("TipoMovimentacaoCarteiraId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("TipoMovimentacaoCarteiraId");

                    b.ToTable("TTipoMovimentacaoCarteira");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Salario", b =>
                {
                    b.Property<Guid>("SalarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MesId");

                    b.Property<double>("Valor");

                    b.HasKey("SalarioId");

                    b.HasIndex("MesId")
                        .IsUnique();

                    b.ToTable("TSalario");
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Despesa.Despesa", b =>
                {
                    b.HasOne("GNBSys.GerenciaDespesas.Domain.Entities.Mes", "Mes")
                        .WithMany("Despesas")
                        .HasForeignKey("MesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GNBSys.GerenciaDespesas.Domain.Entities.Despesa.TipoDespesa", "TipoDespesa")
                        .WithMany("Despesas")
                        .HasForeignKey("TipoDespesaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Receita.Ativo", b =>
                {
                    b.HasOne("GNBSys.GerenciaDespesas.Domain.Entities.Receita.TipoAtivo", "TipoAtivo")
                        .WithMany("Ativos")
                        .HasForeignKey("TipoAtivoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Receita.AtivoCarteira", b =>
                {
                    b.HasOne("GNBSys.GerenciaDespesas.Domain.Entities.Receita.Ativo", "Ativo")
                        .WithMany("AtivosCarteira")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GNBSys.GerenciaDespesas.Domain.Entities.Receita.Carteira", "Carteira")
                        .WithMany("AtivosCarteira")
                        .HasForeignKey("CarteiraId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Receita.MovimentacaoCarteira", b =>
                {
                    b.HasOne("GNBSys.GerenciaDespesas.Domain.Entities.Receita.Ativo", "Ativo")
                        .WithMany("MovimentacoesCarteira")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GNBSys.GerenciaDespesas.Domain.Entities.Receita.Carteira", "Carteira")
                        .WithMany("MovimentacoesCarteira")
                        .HasForeignKey("CarteiraId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GNBSys.GerenciaDespesas.Domain.Entities.Mes", "Mes")
                        .WithMany("MovimentacoesCarteira")
                        .HasForeignKey("MesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GNBSys.GerenciaDespesas.Domain.Entities.Receita.TipoMovimentacaoCarteira", "TipoMovimentacaoCarteira")
                        .WithMany("MovimentacoesCarteira")
                        .HasForeignKey("TipoMovimentacaoCarteiraId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GNBSys.GerenciaDespesas.Domain.Entities.Salario", b =>
                {
                    b.HasOne("GNBSys.GerenciaDespesas.Domain.Entities.Mes", "Mes")
                        .WithOne("Salario")
                        .HasForeignKey("GNBSys.GerenciaDespesas.Domain.Entities.Salario", "MesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
